#-------------------------------------------------------------
# Server config
# 伺服器設定
#-------------------------------------------------------------

#伺服器連接通訊PORT設定 (預設值一般無須變更)
GameserverPort=2000
GRANT ALL PRIVILEGES ON `8.5`.* TO 'root'@'localhost';
FLUSH PRIVILEGES;

URL=jdbc:mysql://localhost/8.5?useUnicode=true&characterEncoding=utf8
Login=root
Password=root

#時區設定 
#Taiwan:Asia/Taipei       #Janpan:Asia/Tokyo 
#HongKong:Asia/Hong_Kong  #China:Etc/GMT+8
#Standard:UTC             #U.S.A:America/New_York
#You can get all available TimeZone from docs/TimeZone.txt
TimeZone = Asia/Taipei

